version: "2"
services:
  node:
    container_name: bh_node
    hostname: bh_node
    working_dir: /home/node/app
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - './:/home/node/app'
    ports:
      - '4000:4000'
      - "56745:56745"
    links:
      - 'postgres:postgres'
  postgres:
    container_name: bh_postgres
    hostname: bh_postgres
    build: './docker/postgres'
    working_dir: /home/psql
    volumes:
      - './sql:/home/psql/sql'
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432"
