branches:
  except:
  - DB_SETUP
  only:
  - master
  - DEV
language: node_js
node_js: 11.9.0
sudo: required
services:
- docker
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.1
  - secure: eugiXwjwfgl9k6ftFJN9CvA5CxLzsmubjxHoXHxUehyXcO5VHff0KiwVFboGcME9P7s93ZGyRYihY2gEfd7yMHBEIeSqvBv2CNKXDgM7ycskyFcYrfHUeeMKZPCxh17C1Hpz7TE8/qj3NVPUu5ds6W4eUyJByfB3jJ/ofKjpCsEHEUhWp1oNjTGlfhSD8Rx74jWdIWs6MUuoyy9LyxGoqmtUmYg5S9V4euTiPYkyU+QHUz5PgErV2LMmBUSSRU/8ok9168By0J/9qDkPizt8+y4OEWDW0pYEwUnQyY9xiraTTK1vqVzNBLY/CDruE4dGgimx/oQkeC9jcomUzKTcr7IoLpbNwKeOLaKVKgcUqRw70NagwHFZeh+3/AcwZqbRvGm+Pt08AzzneQGA6rcoFsBeXnsde70TI/nXBQJ20vUe7PkJ5ry7yDimpZ4Nn7VVpqEtM48uoEOnQGZHZG4cKaf1luxJDGLepIPhVhSukdaVOVgYUP1pVDUctzEmvB5sesvSOdvbnwVdKLslghUdcvsXTwh78fEARPduMz7OcpYSMFioLG3u24Kn6Bp0PsJX/KZ6KzDf/0co1CgC8Bk7IGaq+iJZ0zpef1BagD8P3aU5OEVRfcIGTMFjAt9+Y7/rNBCo2dzasKSqQowTY1LxlQGUwvQA0z2BznJZVilElY0=
  - secure: NjSkKZdw8FwtepRNsJiMXJ0/izoMfCYko9VyThAbXiQFizPUr+erRtfBJ59Pf6lonD6FNnSwi9X75eDp80IfZP/pFpTBdVh3e8CXuLgONuvxDMiQQytpSJw0iZxIQNWyAzJYs6G3v9JQU5yPQx2mkwoZ2NkrGHPV2uoyDFRuMwo3ZA30xGE+ayB05cQSTupPBkyVX9MykNoiTHPMn5evFkfcUdQi4M8JbLTG1GmOyPpejMusdhRJrYkBwfgJIuDrfPVvRw5eLI6YsC37nM0Yd3/vMDCln9Yl6Dc59qylpHRPBT9+ej3o9Ercz4a6NZ7wpgUKnkfW/kPllINNxZ6FRtc543Rgf8reV6H9Pau58M8KIs6dsVGBz+zkCrP8eiY4gRbQG6kkkh6ayv27CqNhdapQ86mdmDo5tzDU4fuJru7s4Sl+fYGtslT6/CEu4xGTPxrrel6FJ02GeZFBq92PBD0eFWPYdvAVLA6tdMixbrDH+qDuCs7LOU9lA6u9CUmR0RfY7bOEWJ9RnJrRJquFhDfI5hIirNTKKgTEcsP8G8naoJ0302g700waobYvtLLMS0Ft4IsRB/1p7WcPxblrWVX8e5PXq563/OJYJaZAjatYzjdyVZiCjgnCt1lIRp1uq0SVTvw+spmfTSYHSa1/eH/KrncVsyjTmuVvMsJK1zE=
cache: npm
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- heroku plugins:install @heroku-cli/plugin-container-registry
before_script:
- cd ./[BACK]
- npm install
- docker-compose build
- docker-compose up -d
- docker exec -it bh_node npm install
- cd ../[FRONT]
- npm install
- npm run test
- npm run build
script:
- docker ps
deploy:
  provider: heroku
  api_key:
    secure: RQe5Z/HskzIg+fXTpW/hQzzUzMImaG7/Q788jN3Bv9cMDlXzVNHeOpnqeBtToThxUle8Dz9pJOT2KVJprrQaaVMpwspLpggkFoGdJuPgMc9ctXpmEgkD8p69D/nxPJiRqDZ5jn5Ziuca8BOs3jQA/cTbZJCRT+HyBwLJrWSZeUoLSRdoOsOFT27E8PXaIHtiWOhAPRBozzF598KMMPoQY8khroCVo6jcuCmOuvt4ytBLv7PK/lZ2Nt2I5HKJktIpoSLWgOMbXDFrM7CzChDo9uyzUmx/Qwfm3nK/sbbJZlNAWG3TZms88G/gKFzTWGCygtbB2FiDtYBngrjTKMx5vmTYAY/phLFQSO7DgseVOg6woR/Eff0mEI9s8JW8EMnBHYjUUgzjv85MqabsLxMIrjbWqWJRSt6MqKmLwAa/1gWCZD4foX5/mMo2QXoMLcYpHj81oOb2PlEa3UnW++uqjnpnW6Hkz+d2wJcE5kP+olgYqb8h7Riz7uj8Iu/hB2lyoJO3NPDDSUM5NRuZfxdoWIcn6xzWQBUkZ782JrPyS0+jPwg9yUahEbB08TMn0k2IUHAzQBI2X0/J7BTX7PZOuj3LLQPhWeCM1TQXdxg4Yqrt6mtJQpGo4tLj3S4kzotS6ZNe6eYGV+9Vgkf5Pz8xgdy+5JsweIkThTgIfRAqgeI=
after_script:
- docker-compose down
after_success:
- docker exec -it bh_node npm run coveralls
