# blacklist
branches:
  except:
    - DB_SETUP

# whitelist
branches:
  only:
    - master
    - DEV

language: node_js
node_js: 11.9.0

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.1

cache: npm

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cd ./[BACK]
  - npm install
  - docker-compose build
  - docker-compose up -d
  - docker exec -it bh_node npm install
  - docker exec -it bh_node /home/node/app/node_modules/.bin/sequelize db:migrate
  - docker exec -it bh_node /home/node/app/node_modules/.bin/sequelize db:seed:all
  - cd ../[FRONT]
  - npm install
  - npm install terser@3.14.1 --save-dev
  - npm run test
  - npm run build
  
script:
# - docker exec -it bh_node node_modules/.bin/sequelize db:migrate
# - npm run travis
  - docker ps
  - docker exec -it bh_node npm run test

after_script:
  - docker-compose down

after_success:
#  - docker exec -it bh_node npm run coveralls
